covid_ppw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tracker/', include('tracker.urls'), name='tracker'),
    path('quiz/', include('quiz.urls'), name='quiz'),
    path('todolist/', include('todolist.urls'), name='todolist'),
    path('report/', include('report.urls'), name='report'),
    path('register/', include('register.urls')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('save/', views.save, name='save'),
]

report/models.py
from django.db import models

# Create your models here.
class Suspect(models.Model):
    nama_suspek = models.CharField(max_length=30)
    alamat = models.CharField(max_length=200)
    tanggal_lahir = models.DateField()
    status = models.CharField(max_length=15)

report/forms.py
from django import forms
from .models import Suspect

class SearchForm(forms.ModelForm):
    class Meta:
        model = Suspect
        fields = ['nama_suspek']

    name_attrs = {
        'class' : 'form-control mb-3',
		'type' : 'text',
		'placeholder' : 'Search by name',
        'name' : 'nama_suspek',
	}

    nama_suspek = forms.CharField(label='', required= True, max_length=50, widget=forms.TextInput(attrs=name_attrs))

class SuspectForm(forms.ModelForm):
    class Meta:
        model = Suspect
        fields = ['nama_suspek', 'alamat', 'tanggal_lahir']

    name_attrs = {
        'class' : 'form-control mb-3',
		'type' : 'text',
		'placeholder' : 'Enter the name',
        'name' : 'nama_suspek',
	}

    address_attrs = {
        'class' : 'form-control mb-3',
		'type' : 'text',
		'placeholder' : 'Address',
        'name' : 'alamat',
	}

    birthdate_attrs = {
        'class' : 'form-control mb-3',
        'type' : 'date',
        'placeholder' : 'Date of Birth',
        'name' : 'tanggal_lahir',
    }

    nama_suspek = forms.CharField(label='', required= True, max_length=50, widget=forms.TextInput(attrs=name_attrs))
    alamat = forms.CharField(label='Alamat', required= True, max_length=200, widget=forms.TextInput(attrs=address_attrs))
    tanggal_lahir = forms.DateField(label='Tanggal Lahir', required= True, widget=forms.TextInput(attrs=birthdate_attrs))
    

report/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from .forms import SuspectForm, SearchForm
from .models import Suspect

response = {}
# Create your views here.

def index(request):
    url_parameter = request.GET.get('q')

    if url_parameter:
        suspects = Suspect.objects.filter(nama_suspek__icontains=url_parameter)
        toggle = "collapse"
        if request.is_ajax():
            html = render_to_string(
                template_name="report/suspects.html", 
                context={"suspects": suspects}
            )

            data_dict = {"html_from_view": html}

            return JsonResponse(data=data_dict, safe=False)
    else:
        toggle = "collapse show"
        suspects = Suspect.objects.all()

    response['suspects'] = suspects
    response['toggle'] = toggle
    response['form'] = AuthenticationForm()

    return render(request, "report/index.html", response)

@login_required(login_url='/login/')
def new(request):
    response = {'inputForm': SuspectForm}
    return render(request, 'report/form.html', response)

def save(request):
    form = SuspectForm(request.POST or None)
    if (form.is_valid() and request.method == 'POST'):
        data_form = form.cleaned_data
        data_input = Suspect()
        data_input.nama_suspek = data_form['nama_suspek']
        data_input.alamat = data_form['alamat']
        data_input.tanggal_lahir = data_form['tanggal_lahir']
        data_input.status = "Not Confirmed"
        data_input.save()
    return redirect('/report/')

report/templates/report/form.html
{% extends 'templates/base.html' %}

{% block meta %}
    <title>Report - Survive COVID</title>
{% endblock meta %}

{% block content %}
<div style="min-height: 600px;">
    <p class="header center">Report The Suspect</p>
    <p class="button-text-dummy center">Complete the suspect’s biodata below.</p>
    </br>
    <form id="form" method="POST" action="/report/save/">
            {% csrf_token %}
            <div class="row">
                <p class="button-text-dummy col-2" style="position: relative; top: 0.5em;">Nama</p>
                <p class="button-text-dummy col-0" style="position: relative; top: 0.5em;">:</p>
                <p class="col">{{ inputForm.nama_suspek }}</p>
            </div>
            <div class="row">
                <p class="button-text-dummy col-2" style="position: relative; top: 0.5em;">Alamat</p>
                <p class="button-text-dummy col-0" style="position: relative; top: 0.5em;">:</p>
                <p class="col">{{ inputForm.alamat }}</p>
            </div>
            <div class="row">
                <p class="button-text-dummy col-2" style="position: relative; top: 0.5em;">Tanggal Lahir</p>
                <p class="button-text-dummy col-0" style="position: relative; top: 0.5em;">:</p>
                <p class="col">{{ inputForm.tanggal_lahir }}</p>
            </div>
            <div class="center">
                <input id="submit" type="submit" class="cta m-5 cta-text text-shadow" value="Submit">
            </div>
    </form>
</div>
    
{% endblock content %}

report/templates/report/index.html
{% extends 'templates/base.html' %}
{% load static %}

{% block meta %}
    <title>Report - Survive COVID</title>
{% endblock meta %}

{% block content %}
<div style="min-height: 600px;">
    <p class="main-title text-glow center">Report</p>
    <p class="button-text-dummy center">This feature is useful for seeing and reporting suspects around you.</p>
    <br>
    <div class="center">
        {% if user.is_authenticated %}
        <a href="{% url 'report:new' %}">
        {% else %}
        <a id=popup>
        {% endif %}
            <button class="cta">
                <p class="cta-text text-shadow">+ New Report</p>
            </button>
        </a>
        <a href="#collapseDataReport" data-toggle="collapse" aria-expanded="false" aria-controls="collapseDataReport">
            <button class="shadow-cta visibility" onclick="toggle('#visibility')">
                <p class="shadow-cta-text" id="visibility">See Report</p>
            </button>
        </a>
    </div>
    <br>

    <div class="collapse" id="collapseDataReport">
        <div class="input-group mb-3">
            <div class="input-group-prepend">
                <span class="input-group-text cta" style="border-radius: 0px;">
                    <div class="cta-text text-shadow" id="search-icon">Search</div>
                </span>
            </div>
            <input type="text" class="form-control" placeholder="Search by name" id="user-input" >
        </div>

        <div class="table-responsive">
            <table id="replaceable-content" class="table table-bordered" style="background-color: var(--green-bg);">
            {% include 'report/suspects.html' %}
            </table>
        </div>
    </div>
</div>

<div class="modal">
    <div class="modal-background"></div>
    <div class="modal-content has-background-white py-5 px-5">
        {% include 'registration/pop_login.html'%}
    </div>
</div>
    
<script type="text/javascript" src="{% static 'report.js' %}"></script>

{% endblock content %}

report/templates/report/suspects.html
{% if suspects %}
<thead>
    <tr>
        <td>Name</td>
        <td>Birth Date</td>
        <td>Address</td>
        <td>Status</td>
    </tr>
</thead>
<tbody>
    {% for person in suspects %}
    <tr>
        <td>{{ person.nama_suspek}}</td>
        <td>{{ person.tanggal_lahir }}</td>
        <td>{{ person.alamat }}</td>
        <td>{{ person.status }}</td>
    </tr>
    {% endfor %}
</tbody>
{% else %}
<p class="text center">No data avalaible<p>
{% endif %}