covid_ppw/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('tracker/', include('tracker.urls'), name='tracker'),
    path('quiz/', include('quiz.urls'), name='quiz'),
    path('todolist/', include('todolist.urls'), name='todolist'),
    path('report/', include('report.urls'), name='report'),
    path('register/', include('register.urls')),
    path('', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
]

tracker/urls.py
from django.urls import path
from . import views

app_name = 'tracker'

urlpatterns = [
    path('', views.index, name='index'),
    path('create_page', views.create_page, name='create_page'),
    path('search_page', views.search_page, name='search_page'),
    path('save_page', views.save_page, name='save_page')
]

tracker/models.py
from django.db import models

# Create your models here.


class Provinsi(models.Model):
    nama = models.CharField(max_length=30)
    kasus_positif = models.IntegerField()
    kasus_sembuh = models.IntegerField()
    kasus_meninggal = models.IntegerField()

tracker/forms.py
from django import forms


class Provinces(forms.Form):
    nama_provinsi = forms.CharField(label='Nama Provinsi Dicari', max_length=30,
                                    required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nama Provinsi Dicari', 'id': 'search-url'}))


class createProvince(forms.Form):
    nama = forms.CharField(label='Nama Provinsi', max_length=30,
                           required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Nama Provinsi'}))

    kasus_positif = forms.IntegerField(label='Kasus Positif',
                                       required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Kasus Positif'}))
    kasus_sembuh = forms.IntegerField(label='Kasus Sembuh',
                                      required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Kasus Sembuh'}))
    kasus_meninggal = forms.IntegerField(label='Kasus Meninggal',
                                         required=True, widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Kasus Meninggal'}))

tracker/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required
from . import forms, models
from django.http import JsonResponse
import urllib3
from json import loads

# Create your views here

def index(request):
    form = { 'search_form': forms.Provinces(), 'form':AuthenticationForm()}
    return render(request, 'tracker/index.html', form)

def search_page(request):
    http = urllib3.PoolManager()
    response = http.request(
        'GET', "https://services5.arcgis.com/VS6HdKS0VfIhv8Ct/arcgis/rest/services/COVID19_Indonesia_per_Provinsi/FeatureServer/0/query?where=1%3D1&outFields=*&outSR=4326&f=json")
    data = loads(response.data.decode('utf-8'))
    data_provinsi = models.Provinsi.objects.all()
    positif = 0
    sembuh = 0
    meninggal = 0
    for i in data['features']:
        positif += i['attributes']['Kasus_Posi']
        sembuh += i['attributes']['Kasus_Semb']
        meninggal += i['attributes']['Kasus_Meni']
    data['features'][34] = {'attributes': {'Provinsi': 'Indonesia', 'Kasus_Posi': positif,
                                                 'Kasus_Semb': sembuh, 'Kasus_Meni': meninggal}}
    for i in data_provinsi:
        p_data = {'attributes': {'Provinsi': i.nama, 'Kasus_Posi': i.kasus_positif,
                               'Kasus_Semb': i.kasus_sembuh, 'Kasus_Meni': i.kasus_meninggal}}
        data['features'].append(p_data)
    return JsonResponse(data)


@login_required(login_url='/login/')
def create_page(request):
    data = {
        'create_form': forms.createProvince()}
    return render(request, 'tracker/create.html', data)

def save_page(request):
    activity_form = forms.createProvince(request.POST or None)
    if request.method == "POST":
        if activity_form.is_valid():
            provinsi = models.Provinsi()
            provinsi.nama = activity_form.cleaned_data['nama']
            provinsi.kasus_positif = activity_form.cleaned_data['kasus_positif']
            provinsi.kasus_sembuh = activity_form.cleaned_data['kasus_sembuh']
            provinsi.kasus_meninggal = activity_form.cleaned_data['kasus_meninggal']
            provinsi.save()
        return redirect('/tracker/')

tracker/templates/tracker/create.html
{% extends 'templates/base.html' %}

{% block meta %}
<title>Tracker - Survive COVID</title>
{% endblock meta %}

{% block content %}
<div style="min-height: 600px;">
    <p class="header">Province 404?</p>
    <p class="button-text-dummy">Be a Hero and Add the Province to Our Database</p>
    <form method="POST" action="/tracker/save_page">
        {% csrf_token %}
        <table>{{ create_form.as_table }}</table>
        <p class="cta-text text-shadow"><input type='submit' class="cta cta-text text-shadow" value="Save" /></p>
    </form>
</div>


{% endblock content %}

tracker/templates/tracker/index.html
{% extends 'templates/base.html' %}

{% block meta %}
<title>Tracker - Survive COVID</title>
{% endblock meta %}

{% block content %}
<p class="main-title text-glow">Status Report Victims of COVID-19</p>
<p class="header">Feeling Worried? Tried Searching</p>
<form method="POST" id="search-form">
    {% csrf_token %}
    <div>
        {{search_form}}
        <p class="cta-text text-shadow">
            <input type='submit' class="cta cta-text text-shadow" value="Search" />
            {% if user.is_authenticated %}
            <a class=" cta cta-text text-shadow" href="{% url 'tracker:create_page' %}">Create Provinsi</a>
            {% else %}
            <a id="popup" class=" cta cta-text text-shadow">Create Provinsi</a>
            {% endif %}
        </p>
    </div>
</form>



<table id="provinces" class="table is-bordered">
    <thead>
        <tr>
            <td>Provinsi</td>
            <td>Kasus Positif</td>
            <td>Kasus Sembuh</td>
            <td>Kasus Meninggal</td>

        </tr>
    </thead>
    <tbody id='tbody'>
    </tbody>
</table>

<div class="modal">
    <div class="modal-background"></div>
    <div class="modal-content has-background-white py-5 px-5">
        {% include 'registration/pop_login.html'%}
    </div>
</div>

{% endblock content %}